INSERT INTO `sys_lookup` (`code`,`value`,label,seq)
VALUES("specialBoilType","包煎","包煎",4),
("specialBoilType","冲服","冲服",5),
("specialBoilType","烊化","烊化",6),
("specialBoilType","另煎","另煎",7),
("specialBoilType","泡服","泡服",8);

update print_field set field_source='takeTimeDate' where id=147;

--以上已执行
insert into `export_xml` (`xml_code`, `xml_name`, `xml_value`) values('reportListByMedicine',NULL,'<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n<receivingList>\r\n	<page-orientation>landscape</page-orientation>\r\n	<title-font-size>20</title-font-size>\r\n	<font-size>11</font-size>\r\n	<body-date-pattern>MM-dd hh:mm</body-date-pattern>\r\n	<body-height>18</body-height>\r\n	<serial-number>yes</serial-number>\r\n	<items name=\"title\">\r\n		<item>\r\n			<titleLabel>药品统计表</titleLabel>\r\n		</item>\r\n	</items>\r\n\r\n	<items name=\"body\">\r\n		<item>\r\n			<fields>medicineName</fields>\r\n			<fieldsLabel>药品名称</fieldsLabel>\r\n			<width>20</width>\r\n			<field-separator>\r\n			</field-separator>\r\n			<field-unit>\r\n			</field-unit>\r\n		</item>\r\n		<item>\r\n			<fields>medicineCode</fields>\r\n			<fieldsLabel>药品编号</fieldsLabel>\r\n			<width>20</width>\r\n			<field-separator>\r\n			</field-separator>\r\n			<field-unit>\r\n			</field-unit>\r\n		</item>\r\n\r\n                <item>\r\n			<fields>standard</fields>\r\n			<fieldsLabel>单位</fieldsLabel>\r\n			<width>20</width>\r\n			<field-separator>\r\n			</field-separator>\r\n			<field-unit>\r\n			</field-unit>\r\n		</item>\r\n		<item>\r\n			<fields>num</fields>\r\n			<fieldsLabel>数量</fieldsLabel>\r\n			<width>20</width>\r\n			<field-separator>\r\n			</field-separator>\r\n			<field-unit>\r\n			</field-unit>\r\n		</item>\r\n		<item>\r\n			<fields>tradeFreight</fields>\r\n			<fieldsLabel>批发价格</fieldsLabel>\r\n			<width>20</width>\r\n			<field-separator>\r\n			</field-separator>\r\n			<field-unit>\r\n			</field-unit>\r\n		</item>\r\n		<item>\r\n			<fields>retailFreight</fields>\r\n			<fieldsLabel>零售价格</fieldsLabel>\r\n			<width>20</width>\r\n			<field-separator>\r\n			</field-separator>\r\n			<field-unit>\r\n			</field-unit>\r\n		</item>\r\n	</items>\r\n</receivingList>');
insert into `export_xml` (`xml_code`, `xml_name`, `xml_value`) values('reportListBySettle',NULL,'<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n<receivingList>\r\n	<page-orientation>landscape</page-orientation>\r\n	<title-font-size>20</title-font-size>\r\n	<font-size>11</font-size>\r\n	<body-date-pattern>MM-dd hh:mm</body-date-pattern>\r\n	<body-height>18</body-height>\r\n	<serial-number>yes</serial-number>\r\n	<items name=\"title\">\r\n		<item>\r\n			<titleLabel>药品统计表</titleLabel>\r\n		</item>\r\n	</items>\r\n\r\n	<items name=\"body\">\r\n		<item>\r\n			<fields>settleCompanyName</fields>\r\n			<fieldsLabel>结算方名称</fieldsLabel>\r\n			<width>20</width>\r\n			<field-separator>\r\n			</field-separator>\r\n			<field-unit>\r\n			</field-unit>\r\n		</item>\r\n		<item>\r\n			<fields>medicineName</fields>\r\n			<fieldsLabel>药品名称</fieldsLabel>\r\n			<width>20</width>\r\n			<field-separator>\r\n			</field-separator>\r\n			<field-unit>\r\n			</field-unit>\r\n		</item>\r\n		<item>\r\n			<fields>medicineCode</fields>\r\n			<fieldsLabel>药品编号</fieldsLabel>\r\n			<width>20</width>\r\n			<field-separator>\r\n			</field-separator>\r\n			<field-unit>\r\n			</field-unit>\r\n		</item>\r\n\r\n                <item>\r\n			<fields>standard</fields>\r\n			<fieldsLabel>单位</fieldsLabel>\r\n			<width>20</width>\r\n			<field-separator>\r\n			</field-separator>\r\n			<field-unit>\r\n			</field-unit>\r\n		</item>\r\n		<item>\r\n			<fields>num</fields>\r\n			<fieldsLabel>数量</fieldsLabel>\r\n			<width>20</width>\r\n			<field-separator>\r\n			</field-separator>\r\n			<field-unit>\r\n			</field-unit>\r\n		</item>\r\n		<item>\r\n			<fields>tradeFreight</fields>\r\n			<fieldsLabel>批发价格</fieldsLabel>\r\n			<width>20</width>\r\n			<field-separator>\r\n			</field-separator>\r\n			<field-unit>\r\n			</field-unit>\r\n		</item>\r\n		<item>\r\n			<fields>retailFreight</fields>\r\n			<fieldsLabel>零售价格</fieldsLabel>\r\n			<width>20</width>\r\n			<field-separator>\r\n			</field-separator>\r\n			<field-unit>\r\n			</field-unit>\r\n		</item>\r\n	</items>\r\n</receivingList>');
insert into `export_xml` (`xml_code`, `xml_name`, `xml_value`) values('reportListByHospital',NULL,'<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n<receivingList>\r\n	<page-orientation>landscape</page-orientation>\r\n	<title-font-size>20</title-font-size>\r\n	<font-size>11</font-size>\r\n	<body-date-pattern>MM-dd hh:mm</body-date-pattern>\r\n	<body-height>18</body-height>\r\n	<serial-number>yes</serial-number>\r\n	<items name=\"title\">\r\n		<item>\r\n			<titleLabel>药品统计表</titleLabel>\r\n		</item>\r\n	</items>\r\n\r\n	<items name=\"body\">\r\n		<item>\r\n			<fields>hospitalCompany</fields>\r\n			<fieldsLabel>医院名称</fieldsLabel>\r\n			<width>20</width>\r\n			<field-separator>\r\n			</field-separator>\r\n			<field-unit>\r\n			</field-unit>\r\n		</item>\r\n		<item>\r\n			<fields>medicineName</fields>\r\n			<fieldsLabel>药品名称</fieldsLabel>\r\n			<width>20</width>\r\n			<field-separator>\r\n			</field-separator>\r\n			<field-unit>\r\n			</field-unit>\r\n		</item>\r\n		<item>\r\n			<fields>medicineCode</fields>\r\n			<fieldsLabel>药品编号</fieldsLabel>\r\n			<width>20</width>\r\n			<field-separator>\r\n			</field-separator>\r\n			<field-unit>\r\n			</field-unit>\r\n		</item>\r\n\r\n                <item>\r\n			<fields>standard</fields>\r\n			<fieldsLabel>单位</fieldsLabel>\r\n			<width>20</width>\r\n			<field-separator>\r\n			</field-separator>\r\n			<field-unit>\r\n			</field-unit>\r\n		</item>\r\n		<item>\r\n			<fields>num</fields>\r\n			<fieldsLabel>数量</fieldsLabel>\r\n			<width>20</width>\r\n			<field-separator>\r\n			</field-separator>\r\n			<field-unit>\r\n			</field-unit>\r\n		</item>\r\n		<item>\r\n			<fields>tradeFreight</fields>\r\n			<fieldsLabel>批发价格</fieldsLabel>\r\n			<width>20</width>\r\n			<field-separator>\r\n			</field-separator>\r\n			<field-unit>\r\n			</field-unit>\r\n		</item>\r\n		<item>\r\n			<fields>retailFreight</fields>\r\n			<fieldsLabel>零售价格</fieldsLabel>\r\n			<width>20</width>\r\n			<field-separator>\r\n			</field-separator>\r\n			<field-unit>\r\n			</field-unit>\r\n		</item>\r\n	</items>\r\n</receivingList>');

insert into `print_field` (`id`, `field_name`, `field_type`, `field_source`, `field_para`, `display_text`, `display_width`, `display_height`, `is_hidden`) values
('151','医生编号','text',"doctorCode",'text_r:|replace:','00001','200','20','0'),
('152','审方员工号','text',"checkBillCode",'text_r:|replace:','00001','200','20','0');

--以上已执行
update print_field set field_name='药品-批发金额' id=410;
insert into `print_field` (`id`, `field_name`, `field_type`, `field_source`, `field_para`, `display_text`, `display_width`, `display_height`, `is_hidden`) 
values('412','药品-单贴金额','list|text','transferMedicineList','list:0|field:moneyEvery','300','80','20','0');
update print_field set field_type='money' where id=104;

insert into sys_shipping_state(state_id,state_name,old_state_id) 
values(2,'已配药接方',2),(93,'已开始配送',93);

/**
 * 以上在院内正式与uat都已执行-- by fenglei 2018/2/1
 */
