/*20171129*/
insert into sys_function(name,code,module_id)values('接方扫描','ACCEPT_SCAN',23),
('配药扫描','DISPENSE_SCAN',23),
('复核扫描','RE_CHECK_SCAN',23),
('浸泡扫描','SOAK_SCAN',23),
('开始煎煮扫描','START_DECOCT_SCAN',23),
('收膏扫描','BOIL_SCAN',23),
('包装扫描','PACK_SCAN',23),
('巡查扫描','PATROL_SCAN',23),
('处方记录查询','RECIPE_HISTORY',23),
('配方抽检','DISPENSE_PATROL',23),
('煎药抽检','DECOCT_PATROL',23),
('结束煎煮','END_DECOCT_SCAN',23),
('调拨请求','ALLOCATE_REQUEST',23),
('调拨请求确认','ALLOCATE_RESPONSE',23),
('智能派工','ZN_ALLOT',23),
('浓缩操作','CONCENTRATE_SCAN',23),
('先煎药品','FIRST_MEDICINE',23),
('后下药品','AFTER_MEDICINE',23),
('审方扫描','CHECK_BILL',23);
insert into sys_role_function(role_id,function_id)select 28,id from sys_function where id>21;
insert into sys_config(name,value,type,comments) value('MAX_SOAK_TIME','20',0,'最大浸泡时间');
insert into sys_config(name,value,type,comments)values('ACCEPT_CHECK_NOT_THROUGH','N',0,'是否支持复核不通过'),
('MUST_CHECK_BILL','N',0,'是否需要审方'),
('TCMPHONE_VERSION_NUMBER','2.4',0,'app版本'),
('TCMPHONE_USER','0',0,'是否支持复核不通过'),
('PACKING_TAG_PRINTER','N',0,'煎药机配置'),
('SHOW_PRINT_SC','N',0,'显示打印按钮'),
('MUST_SUBSIDE','N',0,'是否沉淀'),
('SUBSIDE_TIME','30',0,'沉淀时间'),
('ALLOW_FORCE_PASS','N',0,'是否允许强制通过'),
('IS_CHECK_EXPRESSCODE','N',0,'是否需要验证快递号'),
('IS_DELIVERY_BILL','N',0,'是否有发货流程'),
('IS_RECIPE_PICKING','N',0,'是否有领料流程');
